parameters:
  agent: ER
  update: GSS
  retrieve: random
  mem_size: 5000
  learning_rate: 0.1
  weight_decay: 0
  eps_mem_batch: 10
  gss_batch_size: 10
  gss_mem_strength: 10
  ncm_trick: True
  model_name: GSS_5k_ncm
